### ISSUE TITLE
Research moral & social consequences

### ISSUE THREAD

**Issue by tryggvigy** [plottarar/Research#3]
- Are there any legal issues with creating an API like this?
- Is there a conceivable way of people getting hurt for an API like this?
- What is twitters view on projects like this

**Comment by magtastic** [comment]
Is this closed @tryggvigy?? What was the outcome?? One more action like this and you are fired!

**Comment by tryggvigy** [comment]
@magtastic 
![life uh find a way - imgur](https://user-images.githubusercontent.com/2373958/35803110-e509b0fe-0a72-11e8-8692-35e5b21e828b.gif)
